// src/utils/creatomate/fonts.ts

import { FontStyle } from "./font-types";

export const fontStyles: FontStyle[] = [
  {
    id: 1,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-1.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffffff",
      font_family: "Oswald",
      font_weight: "600",
      text_transform: "uppercase",
      stroke_color: "#000000",
      font_size: "150px",
      stroke_width: "7.6px",
      text_shadow: "5px 5px 2px #000000",
    },
  },
  {
    id: 2,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-2.png",
    styles: {
      y: "82%",
      text_transform: "uppercase",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#f8e71c",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      font_size: "150px",
      stroke_width: "8.4px",
      text_shadow: "5px 5px 2px #000000",
    },
  },
  {
    id: 3,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-3.png",
    styles: {
      y: "82%",
      text_transform: "uppercase",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffffff",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      text_align: "center",
      font_size: "150px",
      stroke_width: "6.2px",
      text_shadow: "5px 5px 10px #000000",
    },
  },
  {
    id: 4,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-4.png",
    styles: {
      y: "82%",
      text_transform: "uppercase",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#f8e71c",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      text_align: "center",
      font_size: "150px",
      stroke_width: "6.2px",
      text_shadow: "5px 5px 10px #000000",
    },
  },
  {
    id: 5,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-5.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      font_size: "150px",
      text_align: "center",
      fill_color: "#c12bff",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 10px #000000",
      stroke_color: "#ffffff",
      stroke_width: "6.4px",
      text_transform: "uppercase",
    },
  },
  {
    id: 6,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-6.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#8effd4",
      font_size: "150px",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 2px #000000",
      stroke_color: "#000000",
      stroke_width: "8.4px",
      text_align: "center",
      text_transform: "uppercase",
    },
  },
  {
    id: 7,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-7.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff0000",
      stroke: "#000000",
      font_size: "150px",
      font_style: "italic",
      text_align: "center",
      font_family: "Luckiest Guy",
      font_weight: 400,
      text_shadow: "5px 5px 10px #000000",
      stroke_width: "14px",
      stroke_color: "#ffffff",
      text_transform: "uppercase",
    },
  },
  {
    id: 8,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-8.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffffff",
      stroke: "#000000",
      font_size: "150px",
      text_align: "center",
      font_family: "Titan One",
      text_shadow: "5px 5px 10px #000000",
      stroke_width: "9.4px",
      text_transform: "lowercase",
      stroke_color: "#000000",
    },
  },
  {
    id: 9,
    preview_image: "https://cdn-crayo.com/crayo-admin/subtitles/template-9.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#1100ff",
      stroke: "#85afff",
      font_size: "150px",
      text_align: "center",
      font_family: "Bungee",
      text_shadow: "5px 5px 10px #384292",
      stroke_width: "14px",
      text_transform: "uppercase",
      stroke_color: "#85afff",
    },
  },
  {
    id: 10,
    preview_image:
      "https://cdn-crayo.com/crayo-admin/subtitles/template-10.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#2ffb00",
      stroke: "#000000",
      font_size: "150px",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 2px #000000",
      stroke_width: "10.8px",
      stroke_color: "#000000",
      text_align: "center",
      text_transform: "uppercase",
    },
  },
  {
    id: 11,
    preview_image:
      "https://cdn-crayo.com/crayo-admin/subtitles/template-11.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff0000",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      text_align: "center",
      text_transform: "uppercase",
      font_size: "150px",
      stroke_width: "6.2px",
      text_shadow: "5px 5px 10px #000000",
    },
  },
  {
    id: 12,
    preview_image:
      "https://cdn-crayo.com/crayo-admin/subtitles/template-12.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#000000",
      stroke: "#ffffff",
      font_size: "150px",
      text_align: "center",
      font_family: "Sigmar",
      text_shadow: "5px 5px 2px #000000",
      stroke_width: "5.6px",
      stroke_color: "#ffffff",
      text_transform: "uppercase",
    },
  },
  {
    id: 13,
    preview_image:
      "https://cdn-crayo.com/crayo-admin/subtitles/template-13.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff7c00",
      stroke: "#ffffff",
      font_size: "150px",
      text_align: "center",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 9px #000000",
      stroke_width: "5.6px",
      stroke_color: "#ffffff",
      text_transform: "uppercase",
    },
  },
  {
    id: 14,
    preview_image:
      "https://cdn-crayo.com/crayo-admin/subtitles/template-14.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#fcff00",
      stroke: "#000000",
      font_size: "150px",
      text_align: "center",
      font_family: "Titan One",
      text_shadow: "5px 5px 2px #000000",
      stroke_width: "7.6px",
      font_weight: "600",
      stroke_color: "#000000",
      text_transform: "uppercase",
    },
  },
  {
    id: 15,
    preview_image:
      "https://cdn-crayo.com/crayo-admin/subtitles/template-15.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00b2",
      stroke: "#ffffff",
      font_size: "150px",
      text_align: "center",
      font_family: "Sigmar",
      text_shadow: "5px 5px 10px #000000",
      stroke_width: "8px",
      stroke_color: "#ffffff",
      font_style: "italic",
      font_weight: 400,
      text_transform: "uppercase",
    },
  },
];
