// src/utils/creatomate/fonts.ts

import { FontStyle } from "./font-types";

export const fontStyles: FontStyle[] = [
  {
    id: 1,
    preview_image: "/fonts/font-1.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffffff",
      font_family: "Oswald",
      font_weight: "600",
      text_transform: "uppercase",
      stroke_color: "#000000",
      font_size: "150px",
      stroke_width: "7.6px",
      text_shadow: "5px 5px 2px #000000",
    },
  },
  {
    id: 2,
    preview_image: "/fonts/font-2.png",
    styles: {
      y: "82%",
      text_transform: "uppercase",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#f8e71c",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      font_size: "150px",
      stroke_width: "8.4px",
      text_shadow: "5px 5px 2px #000000",
    },
  },
  {
    id: 3,
    preview_image: "/fonts/font-3.png",
    styles: {
      y: "82%",
      text_transform: "uppercase",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffffff",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      text_align: "center",
      font_size: "150px",
      stroke_width: "6.2px",
      text_shadow: "5px 5px 10px #000000",
    },
  },
  {
    id: 4,
    preview_image: "/fonts/font-4.png",
    styles: {
      y: "82%",
      text_transform: "uppercase",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#f8e71c",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      text_align: "center",
      font_size: "150px",
      stroke_width: "6.2px",
      text_shadow: "5px 5px 10px #000000",
    },
  },
  {
    id: 5,
    preview_image: "/fonts/font-5.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      font_size: "150px",
      text_align: "center",
      fill_color: "#c12bff",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 10px #000000",
      stroke_color: "#ffffff",
      stroke_width: "6.4px",
      text_transform: "uppercase",
    },
  },
  {
    id: 6,
    preview_image: "/fonts/font-6.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#8effd4",
      font_size: "150px",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 2px #000000",
      stroke_color: "#000000",
      stroke_width: "8.4px",
      text_align: "center",
      text_transform: "uppercase",
    },
  },
  {
    id: 7,
    preview_image: "/fonts/font-7.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff0000",
      font_size: "150px",
      font_style: "italic",
      text_align: "center",
      font_family: "Luckiest Guy",
      font_weight: 400,
      text_shadow: "5px 5px 10px #000000",
      stroke_width: "14px",
      stroke_color: "#ffffff",
      text_transform: "uppercase",
    },
  },
  {
    id: 8,
    preview_image: "/fonts/font-8.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffffff",
      font_size: "150px",
      text_align: "center",
      font_family: "Titan One",
      text_shadow: "5px 5px 10px #000000",
      stroke_width: "9.4px",
      text_transform: "lowercase",
      stroke_color: "#000000",
    },
  },
  {
    id: 9,
    preview_image: "/fonts/font-9.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#1100ff",
      font_size: "150px",
      text_align: "center",
      font_family: "Bungee",
      text_shadow: "5px 5px 10px #384292",
      stroke_width: "14px",
      text_transform: "uppercase",
      stroke_color: "#85afff",
    },
  },
  {
    id: 10,
    preview_image: "/fonts/font-10.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#2ffb00",
      font_size: "150px",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 2px #000000",
      stroke_width: "10.8px",
      stroke_color: "#000000",
      text_align: "center",
      text_transform: "uppercase",
    },
  },
  {
    id: 11,
    preview_image: "/fonts/font-11.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff0000",
      font_family: "Oswald",
      font_weight: "600",
      stroke_color: "#000000",
      text_align: "center",
      text_transform: "uppercase",
      font_size: "150px",
      stroke_width: "6.2px",
      text_shadow: "5px 5px 10px #000000",
    },
  },
  {
    id: 12,
    preview_image: "/fonts/font-12.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#000000",
      font_size: "150px",
      text_align: "center",
      font_family: "Sigmar",
      text_shadow: "5px 5px 2px #000000",
      stroke_width: "5.6px",
      stroke_color: "#ffffff",
      text_transform: "uppercase",
    },
  },
  {
    id: 13,
    preview_image: "/fonts/font-13.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff7c00",
      font_size: "150px",
      text_align: "center",
      font_family: "Luckiest Guy",
      text_shadow: "5px 5px 9px #000000",
      stroke_width: "5.6px",
      stroke_color: "#ffffff",
      text_transform: "uppercase",
    },
  },
  {
    id: 14,
    preview_image: "/fonts/font-14.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#fcff00",
      font_size: "150px",
      text_align: "center",
      font_family: "Titan One",
      text_shadow: "5px 5px 2px #000000",
      stroke_width: "7.6px",
      font_weight: "600",
      stroke_color: "#000000",
      text_transform: "uppercase",
    },
  },
  {
    id: 15,
    preview_image: "/fonts/font-15.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00b2",
      font_size: "150px",
      text_align: "center",
      font_family: "Sigmar",
      text_shadow: "5px 5px 10px #000000",
      stroke_width: "8px",
      stroke_color: "#ffffff",
      font_style: "italic",
      font_weight: 400,
      text_transform: "uppercase",
    },
  },
  {
    id: 16,
    preview_image: "/fonts/font-16.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff5733",
      font_family: "Gloria Hallelujah",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 17,
    preview_image: "/fonts/font-17.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33bbff",
      font_family: "Rock Salt",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #111111",
    },
  },
  {
    id: 18,
    preview_image: "/fonts/font-18.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffcc00",
      font_family: "Varela Round",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 12px #000000",
    },
  },
  {
    id: 19,
    preview_image: "/fonts/font-19.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff66ff",
      font_family: "Lobster",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "6px",
      text_shadow: "5px 5px 15px #444444",
    },
  },
  {
    id: 20,
    preview_image: "/fonts/font-20.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ff99",
      font_family: "Sigmar",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 10px #000000",
    },
  },
  // Additional font styles with similar structure...
  {
    id: 21,
    preview_image: "/fonts/font-21.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff44cc",
      font_family: "Quicksand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 22,
    preview_image: "/fonts/font-22.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#44ff77",
      font_family: "Handlee",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 23,
    preview_image: "/fonts/font-23.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffbb44",
      font_family: "Satisfy",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 24,
    preview_image: "/fonts/font-24.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ccff",
      font_family: "Arizonia",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 25,
    preview_image: "/fonts/font-25.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff3377",
      font_family: "Cookie",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 26,
    preview_image: "/fonts/font-26.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#77ff33",
      font_family: "Russo One",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 27,
    preview_image: "/fonts/font-27.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#cc00ff",
      font_family: "Noto Sans",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 28,
    preview_image: "/fonts/font-28.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff6600",
      font_family: "Ubuntu",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 29,
    preview_image: "/fonts/font-29.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#99ff33",
      font_family: "Indie Flower",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 30,
    preview_image: "/fonts/font-30.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#336699",
      font_family: "Sofia",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 10px #000000",
    },
  },
  {
    id: 31,
    preview_image: "/fonts/font-31.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff5733",
      font_family: "Quicksand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 32,
    preview_image: "/fonts/font-32.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff66cc",
      font_family: "Gochi Hand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 33,
    preview_image: "/fonts/font-33.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ccff",
      font_family: "Satisfy",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 34,
    preview_image: "/fonts/font-34.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffcc00",
      font_family: "Arizonia",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 35,
    preview_image: "/fonts/font-35.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#66ff66",
      font_family: "Rock Salt",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 36,
    preview_image: "/fonts/font-36.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff7777",
      font_family: "Rubik",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 37,
    preview_image: "/fonts/font-37.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#003366",
      font_family: "Gloock",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "2px 2px 12px #000000",
    },
  },
  {
    id: 38,
    preview_image: "/fonts/font-38.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff0077",
      font_family: "Amatic SC",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 39,
    preview_image: "/fonts/font-39.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ccff",
      font_family: "Shadows Into Light",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 40,
    preview_image: "/fonts/font-40.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9966",
      font_family: "Quicksand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 41,
    preview_image: "/fonts/font-41.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffb3e6",
      font_family: "Viga",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 42,
    preview_image: "/fonts/font-42.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#cc00cc",
      font_family: "Dancing Script",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 43,
    preview_image: "/fonts/font-43.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffb366",
      font_family: "Merienda",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 44,
    preview_image: "/fonts/font-44.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#66ccff",
      font_family: "Righteous",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 45,
    preview_image: "/fonts/font-45.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9933",
      font_family: "Patrick Hand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 46,
    preview_image: "/fonts/font-46.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#9900cc",
      font_family: "Noto Serif",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 47,
    preview_image: "/fonts/font-47.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffbb00",
      font_family: "Lobster Two",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 48,
    preview_image: "/fonts/font-48.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9933",
      font_family: "Spectral",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 49,
    preview_image: "/fonts/font-49.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#cc0033",
      font_family: "Lora",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 50,
    preview_image: "/fonts/font-50.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ccff00",
      font_family: "Montserrat Alternates",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "2px 2px 10px #000000",
    },
  },
  {
    id: 51,
    preview_image: "/fonts/font-51.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff5733",
      font_family: "Poppins",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "6px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 52,
    preview_image: "/fonts/font-52.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9933",
      font_family: "Montserrat",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 53,
    preview_image: "/fonts/font-53.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ff57",
      font_family: "Raleway",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 54,
    preview_image: "/fonts/font-54.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33bbff",
      font_family: "Bebas Neue",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 55,
    preview_image: "/fonts/font-55.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ddff",
      font_family: "Lobster",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 56,
    preview_image: "/fonts/font-56.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff7733",
      font_family: "Pacifico",
      font_weight: "500",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 57,
    preview_image: "/fonts/font-57.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ddff",
      font_family: "Anton",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "6px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 58,
    preview_image: "/fonts/font-58.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00cc",
      font_family: "Bangers",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 59,
    preview_image: "/fonts/font-59.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33aaff",
      font_family: "Caveat",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 60,
    preview_image: "/fonts/font-60.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffbb33",
      font_family: "Playfair Display",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 61,
    preview_image: "/fonts/font-61.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#9933ff",
      font_family: "Righteous",
      font_weight: "800",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 62,
    preview_image: "/fonts/font-62.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ff99",
      font_family: "Fredoka One",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 63,
    preview_image: "/fonts/font-63.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff33cc",
      font_family: "Permanent Marker",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 64,
    preview_image: "/fonts/font-64.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00ff",
      font_family: "Shrikhand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 65,
    preview_image: "/fonts/font-65.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#77ff33",
      font_family: "Baloo Bhai 2",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 66,
    preview_image: "/fonts/font-66.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff5733",
      font_family: "Gloria Hallelujah",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 67,
    preview_image: "/fonts/font-67.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33bbff",
      font_family: "Rock Salt",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 68,
    preview_image: "/fonts/font-68.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffcc00",
      font_family: "Varela Round",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 10px #000000",
    },
  },
  {
    id: 69,
    preview_image: "/fonts/font-69.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9966",
      font_family: "Lobster",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 70,
    preview_image: "/fonts/font-70.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ff33",
      font_family: "Pacifico",
      font_weight: "500",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 71,
    preview_image: "/fonts/font-71.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ddff",
      font_family: "Anton",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "6px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 72,
    preview_image: "/fonts/font-72.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00cc",
      font_family: "Bangers",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 73,
    preview_image: "/fonts/font-73.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33aaff",
      font_family: "Caveat",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 74,
    preview_image: "/fonts/font-74.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffbb33",
      font_family: "Playfair Display",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 75,
    preview_image: "/fonts/font-75.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#9933ff",
      font_family: "Righteous",
      font_weight: "800",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 76,
    preview_image: "/fonts/font-76.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ff99",
      font_family: "Fredoka One",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 77,
    preview_image: "/fonts/font-77.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff33cc",
      font_family: "Permanent Marker",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 78,
    preview_image: "/fonts/font-78.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00ff",
      font_family: "Shrikhand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 79,
    preview_image: "/fonts/font-79.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#77ff33",
      font_family: "Baloo Bhai 2",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 80,
    preview_image: "/fonts/font-80.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff5733",
      font_family: "Gloria Hallelujah",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 81,
    preview_image: "/fonts/font-81.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33bbff",
      font_family: "Rock Salt",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 82,
    preview_image: "/fonts/font-82.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffcc00",
      font_family: "Varela Round",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 10px #000000",
    },
  },
  {
    id: 83,
    preview_image: "/fonts/font-83.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9966",
      font_family: "Lobster",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 84,
    preview_image: "/fonts/font-84.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ff33",
      font_family: "Pacifico",
      font_weight: "500",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 85,
    preview_image: "/fonts/font-85.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ddff",
      font_family: "Anton",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "6px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 86,
    preview_image: "/fonts/font-86.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00cc",
      font_family: "Bangers",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 87,
    preview_image: "/fonts/font-87.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33aaff",
      font_family: "Caveat",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 88,
    preview_image: "/fonts/font-88.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffbb33",
      font_family: "Playfair Display",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 89,
    preview_image: "/fonts/font-89.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#9933ff",
      font_family: "Righteous",
      font_weight: "800",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 90,
    preview_image: "/fonts/font-90.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ff99",
      font_family: "Fredoka One",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 91,
    preview_image: "/fonts/font-91.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff33cc",
      font_family: "Permanent Marker",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 92,
    preview_image: "/fonts/font-92.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00ff",
      font_family: "Shrikhand",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 93,
    preview_image: "/fonts/font-93.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#77ff33",
      font_family: "Baloo Bhai 2",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 94,
    preview_image: "/fonts/font-94.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff5733",
      font_family: "Gloria Hallelujah",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 95,
    preview_image: "/fonts/font-95.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33bbff",
      font_family: "Rock Salt",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 96,
    preview_image: "/fonts/font-96.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ffcc00",
      font_family: "Varela Round",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "4px",
      text_shadow: "3px 3px 10px #000000",
    },
  },
  {
    id: 97,
    preview_image: "/fonts/font-97.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff9966",
      font_family: "Lobster",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 98,
    preview_image: "/fonts/font-98.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#33ff33",
      font_family: "Pacifico",
      font_weight: "500",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 99,
    preview_image: "/fonts/font-99.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#00ddff",
      font_family: "Anton",
      font_weight: "600",
      font_size: "150px",
      stroke_color: "#000000",
      stroke_width: "6px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
  {
    id: 100,
    preview_image: "/fonts/font-100.png",
    styles: {
      y: "82%",
      x_alignment: "50%",
      y_alignment: "50%",
      fill_color: "#ff00cc",
      font_family: "Bangers",
      font_weight: "700",
      font_size: "150px",
      stroke_color: "#ffffff",
      stroke_width: "5px",
      text_shadow: "3px 3px 15px #000000",
    },
  },
];

export const getRandomFontStyle = (): FontStyle => {
  const randomIndex = Math.floor(Math.random() * fontStyles.length);
  return fontStyles[randomIndex];
};
